<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <DefineConstants>FABLE_COMPILER_PYTHON;FABLE_COMPILER</DefineConstants>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <Import Project="ProcessCore.Common.props" />

  <ItemGroup>
    <Compile Include="Helper\CrossAsync.fs" />
    <Compile Include="Helper\ResizeArray.fs" />
    <Compile Include="Helper\Option.fs" />
    <Compile Include="Helper\Path.fs" />
    <Compile Include="Helper\Regex.fs" />
    <Compile Include="Helper\Ontology.fs" />
    <Compile Include="Helper\Identifier.fs" />
    <Compile Include="DefinedTerm.fs" />
    <Compile Include="FormalParameter.fs" />
    <Compile Include="Annotation.fs" />
    <Compile Include="Administrative.fs" />
    <Compile Include="FragmentSelector.fs" />
    <Compile Include="Graph.fs" />
    <Compile Include="YML\Helpers.fs" />
    <Compile Include="YML\Decode.fs" />
    <Compile Include="YML\Encode.fs" />
    <Compile Include="YML\DefinedTerm.fs" />
    <Compile Include="YML\FormalParameter.fs" />
    <Compile Include="YML\Annotation.fs" />
    <Compile Include="YML\Sample.fs" />
    <Compile Include="YML\Data.fs" />
    <Compile Include="YML\Recipe.fs" />
    <Compile Include="YML\Process.fs" />
    <Compile Include="YML\Organization.fs" />
    <Compile Include="YML\Agent.fs" />
    <Compile Include="YML\ScholarlyArticle.fs" />
    <Compile Include="YML\DataContext.fs" />
    <Compile Include="YML\Dataset.fs" />
    <Compile Include="SQL\Sql.fs" />
    <Compile Include="SQL\Tables.fs" />
    <Compile Include="SQL\RowCodecs.fs" />
    <Compile Include="SQL\Repository.fs" />
    <Compile Include="SQL\Platform\Driver.fs" />
    <Compile Include="SQL\PythonSqliteDriver.fs" />
    <Compile Include="Table.fs" />
    <Compile Include="Table.fs" />
    <Folder Include="Spreadsheet\" />
    <Compile Include="Spreadsheet\CollectionAux.fs" />
    <Compile Include="Spreadsheet\Metadata\Conversions.fs" />
    <Compile Include="Spreadsheet\Metadata\Comment.fs" />
    <Compile Include="Spreadsheet\Metadata\SparseTable.fs" />
    <Compile Include="Spreadsheet\Metadata\Contacts.fs" />
    <Compile Include="Spreadsheet\Metadata\OntologyAnnotation.fs" />
    <Compile Include="Spreadsheet\Metadata\DesignDescriptors.fs" />
    <Compile Include="Spreadsheet\Metadata\Factors.fs" />
    <Compile Include="Spreadsheet\Metadata\Protocols.fs" />
    <Compile Include="Spreadsheet\Metadata\Publication.fs" />
    <Compile Include="Spreadsheet\Metadata\Assays.fs" />
    <Compile Include="Spreadsheet\Metadata\Study.fs" />
    <Compile Include="Spreadsheet\Metadata\Workflow.fs" />
    <Compile Include="Spreadsheet\Metadata\Run.fs" />
    <Compile Include="Spreadsheet\Metadata\OntologySourceReference.fs" />
    <Compile Include="Spreadsheet\AnnotationTable.fs" />
    <Compile Include="Spreadsheet\DatamapTable\DatamapHeader.fs" />
    <Compile Include="Spreadsheet\DatamapTable\DatamapColumn.fs" />
    <Compile Include="Spreadsheet\DatamapTable\DatamapTable.fs" />
    <Compile Include="Spreadsheet\Datamap.fs" />
    <Compile Include="Spreadsheet\ArcAssay.fs" />
    <Compile Include="Spreadsheet\ArcStudy.fs" />
    <Compile Include="Spreadsheet\ArcWorkflow.fs" />
    <Compile Include="Spreadsheet\ArcRun.fs" />
    <Compile Include="Spreadsheet\ArcInvestigation.fs" />
    <Compile Include="ScaffoldReader.fs" />
    <Compile Include="ARC.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fable.Core" />
    <PackageReference Include="YAMLicious" />
    <PackageReference Include="DynamicObj" />
    <PackageReference Include="FsSpreadsheet.Py" />
  </ItemGroup>

</Project>

