<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageTags>ARC;F#;FSharp;dotnet;.Net;bioinformatics;biology;fable-library;datascience;dataplant;nfdi;metadata;fable-dotnet</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <Import Project="ProcessCore.Common.props" />

  <ItemGroup>

    <None Include="index.ts" />
    <None Include="__init__.py" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <Content Include="ProcessCore.Common.props" Pack="true" PackagePath="fable/" />
    <Compile Include="Helper.fs" />
    <Compile Include="DefinedTerm.fs" />
    <Compile Include="FormalParameter.fs" />
    <Compile Include="Annotation.fs" />
    <Compile Include="FragmentSelector.fs" />
    <Compile Include="Graph.fs" />
    <Compile Include="YML\Helpers.fs" />
    <Compile Include="YML\Decode.fs" />
    <Compile Include="YML\Encode.fs" />
    <Compile Include="YML\DefinedTerm.fs" />
    <Compile Include="YML\FormalParameter.fs" />
    <Compile Include="YML\Annotation.fs" />
    <Compile Include="YML\Sample.fs" />
    <Compile Include="YML\Data.fs" />
    <Compile Include="YML\Plan.fs" />
    <Compile Include="YML\Process.fs" />
    <Compile Include="YML\Dataset.fs" />
    <Compile Include="SQL\Sql.fs" />
    <Compile Include="SQL\Tables.fs" />
    <Compile Include="SQL\RowCodecs.fs" />
    <Compile Include="SQL\Repository.fs" />
    <Compile Include="SQL\Platform\Driver.fs" />
    <Compile Include="SQL\SqliteDriver.fs" />
    <Compile Include="Table.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fable.Core" />
    <PackageReference Include="YAMLicious" />
    <PackageReference Include="DynamicObj" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Fable.Package.SDK">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

</Project>
