<Project>

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <FablePackageType>library</FablePackageType>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>nfdi4plants, Lukas Weil, Kevin Schneider</Authors>
    <RepositoryUrl>https://github.com/HLWeil/ProcessCore</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

</Project>