<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Helper.fs" />
    <Compile Include="DefinedTerm.fs" />
    <Compile Include="FormalParameter.fs" />
    <Compile Include="Annotation.fs" />
    <Compile Include="FragmentSelector.fs" />
    <Compile Include="Graph.fs" />
    <Compile Include="YML\Helpers.fs" />
    <Compile Include="YML\Decode.fs" />
    <Compile Include="YML\Encode.fs" />
    <Compile Include="YML\DefinedTerm.fs" />
    <Compile Include="YML\FormalParameter.fs" />
    <Compile Include="YML\Annotation.fs" />
    <Compile Include="YML\Sample.fs" />
    <Compile Include="YML\Data.fs" />
    <Compile Include="YML\Recipe.fs" />
    <Compile Include="YML\Process.fs" />
    <Compile Include="YML\Dataset.fs" />
    <Compile Include="SQL\Sql.fs" />
    <Compile Include="SQL\Tables.fs" />
    <Compile Include="SQL\RowCodecs.fs" />
    <Compile Include="SQL\Repository.fs" />
    <Compile Include="SQL\Platform\Driver.fs" />
    <Compile Include="SQL\PythonSqliteDriver.fs" />
    <Compile Include="Table.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fable.Core" />
    <PackageReference Include="YAMLicious" />
    <PackageReference Include="DynamicObj" />
  </ItemGroup>

</Project>
