module ProcessCore.Spreadsheet.DatamapHeader

open ProcessCore
open ProcessCore.Table
open ProcessCore.Helper
open FsSpreadsheet
open DynamicObj


module DatamapAux = 

    [<Literal>]
    let datamapName = "Datamap"

    let dataHeader = CompositeHeader.Input IOType.Data

    [<Literal>]
    let dataShortHand = "Data"

    let explication = DefinedTerm("Clarification",tan = "http://purl.obolibrary.org/obo/NCIT_C94778")

    [<Literal>]
    let explicationShortHand = "Explication"

    let explicationHeader = CompositeHeader.Parameter explication

    let unit = DefinedTerm("Unit",tan = "http://purl.obolibrary.org/obo/UO_0000000")

    [<Literal>]
    let unitShortHand = "Unit"

    let unitHeader = CompositeHeader.Parameter unit

    let objectType = DefinedTerm("Data Type",tan = "http://purl.obolibrary.org/obo/NCIT_C42645")

    let objectTypeHeader = CompositeHeader.Parameter objectType

    [<Literal>]
    let objectTypeShortHand = "Object Type"

    let labelHeader = CompositeHeader.FreeText "Label"

    [<Literal>]
    let labelShortHand = "Label"

    let descriptionHeader = CompositeHeader.FreeText "Description"

    [<Literal>]
    let descriptionShortHand = "Description"

    let generatedByHeader = CompositeHeader.FreeText "Generated By"

    [<Literal>]
    let generatedByShortHand = "Generated By"

    let allowedHeaders = 
        [dataHeader; explicationHeader; unitHeader; objectTypeHeader; descriptionHeader; generatedByHeader]

    let getOntologyColumn (f : DataContext -> DefinedTerm option) (dataContexts : ResizeArray<DataContext>) = 
        dataContexts
        |> Seq.map (fun dc -> 
            match f dc with
            | Some s -> CompositeCell.Term(s.Name, s.TAN)
            | None -> CompositeCell.Term("", None)
        )
        |> ResizeArray

    let getStringColumn (f : DataContext -> string option) (dataContexts : ResizeArray<DataContext>) = 
        dataContexts
        |> Seq.map (fun dc -> 
            match f dc with
            | Some s -> CompositeCell.FreeText(s)
            | None -> CompositeCell.FreeText("")
        )
        |> ResizeArray

    let setOntologyColumn (f : DataContext -> DefinedTerm option -> unit) (column : CompositeCell []) (dataContexts : ResizeArray<DataContext>) = 
        column
        |> Seq.iteri (fun i cell -> 
            match cell with
            | CompositeCell.Term (name, tan) -> f (dataContexts.[i]) (Some (DefinedTerm(name, ?tan = tan)))
            | _ -> ()
        )

    let setStringColumn (f : DataContext -> string option -> unit) (column : CompositeCell []) (dataContexts : ResizeArray<DataContext>) =
        column
        |> Seq.iteri (fun i cell -> 
            match cell with
            | CompositeCell.FreeText s -> f (dataContexts.[i]) (Some s)
            | _ -> ()
        )

    module SanityChecks =
        
        let rowIndexInBoundaries (row : int) (dataContexts : ResizeArray<DataContext>) = 
            if row < 0 then 
                failwith "Row index must be greater or equal to 0."
            if row >= dataContexts.Count then 
                failwith "Row index must be less than the number of rows."

        let lengthOfNewColumn (newColumn : CompositeCell []) (dataContexts : ResizeArray<DataContext>) = 
            if newColumn.Length <> dataContexts.Count then
                failwith "Length of new column does not match length of data contexts."

module ActivePattern = 

    open Regex.ActivePatterns

    let ontologyAnnotationFromFsCells (tsrCol : int option) (tanCol : int option) (cells : list<FsCell>) : DefinedTerm =
        let cellValues = cells |> List.map (fun c -> c.ValueAsString())
        let tsr = Option.map (fun i -> cellValues.[i]) tsrCol
        let tan = Option.map (fun i -> cellValues.[i]) tanCol
        DefinedTerm(cellValues.[0], ?tan = tan)

    let freeTextFromFsCells (cells : list<FsCell>) : string =
        let cellValues = cells |> List.map (fun c -> c.ValueAsString())
        cellValues.[0]

    let dataFromFsCells (format : int option) (selectorFormat : int option) (cells : list<FsCell>) : Data =
        let cellValues = cells |> List.map (fun c -> c.ValueAsString())
        let format = Option.map (fun i -> cellValues.[i]) format
        let selectorFormat = Option.map (fun i -> cellValues.[i]) selectorFormat
        let path, selector = 
            if cellValues.[0].Contains ("#") then
                let parts = cellValues.[0].Split('#')
                parts.[0], Some parts.[1]
            else
                cellValues.[0], None
        Data(path, ?selector = selector,?encodingFormat = format, ?selectorFormat = selectorFormat)

    let (|Term|_|) (categoryString : string) (cells : FsCell list) : ((FsCell list -> DefinedTerm)) option =
        let (|AC|_|) s =
            if s = categoryString then Some 1 else None
        let (|TSRColumnHeaderRaw|_|) (s : string) =
            if s.StartsWith("Term Source REF") then Some s else None
        let (|TANColumnHeaderRaw|_|) (s : string) =
            if s.StartsWith("Term Accession Number") then Some s else None
        let cellValues = cells |> List.map (fun c -> c.ValueAsString())
        match cellValues with
        | [AC header] -> 
            (ontologyAnnotationFromFsCells None None)
            |> Some
        | [AC header; TSRColumnHeaderRaw _; TANColumnHeaderRaw _] ->
            (ontologyAnnotationFromFsCells (Some 1) (Some 2))
            |> Some
        | [AC header; TANColumnHeaderRaw _; TSRColumnHeaderRaw _] ->
            (ontologyAnnotationFromFsCells (Some 2) (Some 1))
            |> Some
        | _ -> None

    let (|Explication|_|) (cells : FsCell list) =
        match cells with
        | Term DatamapAux.explicationShortHand r ->
            (fun (dc : DataContext) (cells : FsCell list) -> 
                dc.Explication <- Some (r cells)
                dc
            )
            |> Some
        | _ -> None

    let (|Unit|_|) (cells : FsCell list) =
        match cells with
        | Term DatamapAux.unitShortHand r ->
            (fun (dc : DataContext) (cells : FsCell list) -> 
                dc.Unit <- Some (r cells)
                dc
            )
            |> Some
        | _ -> None

    let (|ObjectType|_|) (cells : FsCell list) =
        match cells with
        | Term DatamapAux.objectTypeShortHand r ->
            (fun (dc : DataContext) (cells : FsCell list) -> 
                dc.ObjectType <- Some (r cells)
                dc
            )
            |> Some
        | _ -> None

    let (|Description|_|) (cells : FsCell list) =
        let cellValues = cells |> List.map (fun c -> c.ValueAsString())
        match cellValues with
        | [DatamapAux.descriptionShortHand] -> 
            (fun (dc : DataContext) (cells : FsCell list) -> 
                dc.Description <- freeTextFromFsCells cells |> Option.fromValueWithDefault ""
                dc
            )
            |> Some
        | _ -> None

    let (|GeneratedBy|_|) (cells : FsCell list) =
        let cellValues = cells |> List.map (fun c -> c.ValueAsString())
        match cellValues with
        | [DatamapAux.generatedByShortHand] -> 
            (fun (dc : DataContext) (cells : FsCell list) -> 
                dc.GeneratedBy <- freeTextFromFsCells cells |> Option.fromValueWithDefault ""
                dc
            )
            |> Some
        | _ -> None

    let (|Label|_|) (cells : FsCell list) =
        let cellValues = cells |> List.map (fun c -> c.ValueAsString())
        match cellValues with
        | [DatamapAux.labelShortHand] -> 
            (fun (dc : DataContext) (cells : FsCell list) -> 
                dc.Label <- freeTextFromFsCells cells |> Option.fromValueWithDefault ""
                dc
            )
            |> Some
        | _ -> None

    let (|Data|_|) (cells : FsCell list) =
        let cellValues = cells |> List.map (fun c -> c.ValueAsString())
        match cellValues with
        | DatamapAux.dataShortHand :: cols -> 
            (fun (dc : DataContext) (cells : FsCell list) ->
                let format = cols |> List.tryFindIndex (fun s -> s.StartsWith("Data Format"))  |> Option.map ((+) 1)
                let selectorFormat = cols |> List.tryFindIndex (fun s -> s.StartsWith("Data Selector Format"))  |> Option.map ((+) 1)
                let d = dataFromFsCells format selectorFormat cells
                dc.Data <- d
                dc
            )
            |> Some
               
        | _ -> None

    let (|Comment|_|) (cells : FsCell list) =
        let cellValues = cells |> List.map (fun c -> c.ValueAsString())
        match cellValues with
        | [Comment key] -> 
            (fun (dc : DataContext) (cells : FsCell list) -> 
                let cellValues = cells |> List.map (fun c -> c.ValueAsString())
                let comment = cellValues.[0]
                match dc.TryGetPropertyValue("Comments") with
                | Some (:? ResizeArray<string> as comments) -> 
                    comments.Add(comment)
                | _ -> 
                    let comments = ResizeArray<string>()
                    comments.Add(comment)
                    dc.SetProperty("Comments", comments)
                dc
            )
            |> Some   
        | _ -> None

    let (|Freetext|_|) (cells : FsCell list) =
        let cellValues = cells |> List.map (fun c -> c.ValueAsString())
        match cellValues with
        | [key] -> 
            (fun (dc : DataContext) (cells : FsCell list) -> 
                let cellValues = cells |> List.map (fun c -> c.ValueAsString())
                let comment = cellValues.[0]
                match dc.TryGetPropertyValue("Comments") with
                | Some (:? ResizeArray<string> as comments) -> 
                    comments.Add(comment)
                | _ -> 
                    let comments = ResizeArray<string>()
                    comments.Add(comment)
                    dc.SetProperty("Comments", comments)
                dc
            )
            |> Some   
        | _ -> None

open ActivePattern

let fromFsCells (cells : FsCell list) : DataContext -> FsCell list -> DataContext =
    match cells with
    | Explication r 
    | Unit r 
    | ObjectType r 
    | Description r 
    | GeneratedBy r
    | Label r
    | Data r 
    | Comment r 
    | Freetext r -> 
        fun (dc : DataContext) (cells : FsCell list) -> r dc cells
    | _ -> failwithf "Could not parse data map column: %s" (cells |> List.map (fun c -> c.ValueAsString()) |> String.concat ", ")

let toFsCells (commentKeys : string list) : list<FsCell> = 
    [
        yield! [
            FsCell("Data")
            FsCell("Data Format")
            FsCell("Data Selector Format")
        ]  
        yield! [
            FsCell(DatamapAux.explicationShortHand)
            FsCell("Term Source REF")
            FsCell("Term Accession Number")
        ]
        yield![
            FsCell(DatamapAux.unitShortHand)
            FsCell("Term Source REF")
            FsCell("Term Accession Number")
        ]
        yield![
            FsCell(DatamapAux.objectTypeShortHand)
            FsCell("Term Source REF")
            FsCell("Term Accession Number")
        ]
        yield! [
            FsCell(DatamapAux.descriptionShortHand)
        ]
        yield! [
            FsCell(DatamapAux.generatedByShortHand)
        ]
        yield! [
            FsCell(DatamapAux.labelShortHand)
        ]
        for ck in commentKeys do
            yield FsCell($"Comment [{ck}]")
    ]
